apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
namespace: app

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: api-tls
    type: kubernetes.io/tls
    files:
      - tls.crt=secrets/tls.crt
      - tls.key=secrets/tls.key
