name: Seed Heroku

on:
  workflow_run:
    workflows:
      - Deploy Heroku
    types:
      - completed
  workflow_dispatch:

jobs:
  seed:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.1

      - name: Seed Heroku app
        env:
          API_BASE_URL: ${{ secrets.HEROKU_URL }}
          SEED_WAIT_LIMIT: 120s
        run: |
          set -euo pipefail

          : "${API_BASE_URL:?E2E_BASE_URL secret must be set}"

          go run ./cmd/seed
